### ISSUE TITLE
Permissions for SharePoint Script

### ISSUE THREAD

**Issue by ghost** [Sam360/SAMGoldToolkit#2]
Hi SAM360, actually it is not an issue, I just want to know what kind of permissions the user need to have in SharePoint so its able to collect all the information. Can you guys tell me please? I didn't find any other place to put this doubt.

**Comment by JonMulligan** [comment]
Hi Felipe - You need to be a SharePoint Admin with access to all Web Applications on the server. It's best to run directly on the SharePoint server (rather than remotely) Are you seeing an error when you run it?

**Comment by ghost** [comment]
No, not seeing any error yet. Just avoiding it.

Em seg, 22 de jul de 2019 às 16:57, JonMulligan <notifications@github.com>
escreveu:
